### ISSUE TITLE
Read This Before You Use It

### ISSUE THREAD

**Issue by jeydinpham** [Lemons1337/Discord-Spammer#25]
Let me just make one thing clear:
# Bots cannot join a server without an invite link made with an OAuth scope. 
They cannot join servers and spam unless someone with the Manage Server or Administrator permission lets them in.
So you might as well just go and do something else as this clearly doesn't work, and I'm just speaking theoretically here, I don't even wanna know what the code *does.*

**Comment by clouedoc** [comment]
You should read the code to understand what's happening.
This code is meant for usage with real Discord account tokens.
The bot uses Discord's private v7 API to make them join the target server.

**Comment by jeydinpham** [comment]
So we're talking about self bots now? That's just plainly against ToS

**Comment by jeydinpham** [comment]
lmfao but it doesn't even work lmAo

**Comment by Artizmal** [comment]
> So we're talking about self bots now? That's just plainly against ToS

But you're looking for a bot that will spam? I'm pretty sure that's classified as abuse on their API if you do use a bot and not a self-bot. But besides that, "Sending spam is against our Terms of Service. We might take action against any account, **bot**, or server initiating any of these or similar tactics." So what you're looking for is plainly against ToS as well. Not saying that this is perfectly fine to use without repercussions, as you've stated it's against ToS, but I'm just clearing things up as it seems you're a bit misinformed.

**Comment by jeydinpham** [comment]
Well yeah, I know .-.

**Comment by jeydinpham** [comment]
But it doesn't work anymore so that's that
